### ISSUE TITLE
backup location and system

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#44]
We need a location to store bugsigdb.org backups. Should this be a server with ssh/scp access, a cloud bucket, or something else @tosfos?

**Comment by tosfos** [comment]
Should be all good now

**Comment by tosfos** [comment]
Can this be closed?

**Comment by lgeistlinger** [comment]
@lwaldron input required.

**Comment by lwaldron** [comment]
I can see the file `combined.tar.gz` which contains _resources.tar.gz (22KB), db_snapshot.sql.gz (Zero bytes) and images_snapshot.tar (Zero bytes). Not sure if that's right. I just set up some storage rules, moving versions 2-5 to Coldline, 6 to one year to Archive, and deleting older than a year. Probably don't need a full year of backups, but at the current size the cost is trivial anyways. 

I'd still like to attach to this issue, instructions for doing a full restoration on the Docker container, and to confirm that we're able to do it ourselves.

**Comment by tosfos** [comment]
Do you have your own server (either remote or local) where you can actually perform a restore of the container?

**Comment by lwaldron** [comment]
Since it’s Dockerized we should be able to test it anywhere right, and it
would just be a matter of setting up DNS to actually run it somewhere else?
I’d like to test installing from backup both on a Cloud service and
locally. @jwokaty would you mind testing it once we have procedures?--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

**Comment by jwokaty** [comment]
@lwaldron Sure! I'll test when ready.

**Comment by tosfos** [comment]
> I can see the file combined.tar.gz which contains _resources.tar.gz (22KB)

Do you mean 22 MB? 

We checked all the scripts and everything looks OK with the logs and script. When we checked the file size, we got:

`gsutil ls -l gs://backups.bugsigdb.org/`
 ` 27458773  2021-03-15T10:34:37Z  gs://backups.bugsigdb.org/combined.tar.gz`

**Comment by tosfos** [comment]
[docker-bugsigdb.org-master.zip](https://github.com/waldronlab/BugSigDB/files/6159504/docker-bugsigdb.org-master.zip)

The docker files are attached. Please let me know if you have any questions.

**Comment by lwaldron** [comment]
Here is what I am seeing, yes 22KB (not MB). This is also what I see in the Cloud console, I'll paste a screenshot below. Another thing confusing me is I can't find older versions, even though I set up an object lifecycle. @jwokaty would you also take a look at the [GCP storage browser for bugsigdb](https://console.cloud.google.com/storage/browser?project=bugsigdb) and confirm I'm not doing something terribly wrong?

```bash
lwaldron@wallabe4:~/Downloads$ gsutil ls -l gs://backups.bugsigdb.org/
     22307  2021-03-18T06:00:11Z  gs://backups.bugsigdb.org/combined.tar.gz
TOTAL: 1 objects, 22307 bytes (21.78 KiB)
lwaldron@wallabe4:~/Downloads$ gsutil cp gs://backups.bugsigdb.org/combined.tar.gz .
Copying gs://backups.bugsigdb.org/combined.tar.gz...
/ [1 files][ 21.8 KiB/ 21.8 KiB]                                                
Operation completed over 1 objects/21.8 KiB.                                     
lwaldron@wallabe4:~/Downloads$ md5sum combined.tar.gz
6881fde28b6941c42e56a8decb470fa8  combined.tar.gz
lwaldron@wallabe4:~/Downloads$ ls -l combined.tar.gz 
-rw-rw-r-- 1 lwaldron lwaldron 22307 Mar 18 04:49 combined.tar.gz
lwaldron@wallabe4:~/Downloads$ tar xfz combined.tar.gz 
lwaldron@wallabe4:~/Downloads$ ls -l _resources.tar.gz db_snapshot.sql.gz images_snapshot.tar 
-rw-r--r-- 1 lwaldron lwaldron     0 Mar 18 02:00 db_snapshot.sql.gz
-rw-r--r-- 1 lwaldron lwaldron     0 Mar 18 02:00 images_snapshot.tar
-rw-r--r-- 1 lwaldron lwaldron 22037 Mar 18 02:00 _resources.tar.gz
lwaldron@wallabe4:~/Downloads$ md5sum _resources.tar.gz db_snapshot.sql.gz images_snapshot.tar 
ea512f8e9216344f4244d04ef6199feb  _resources.tar.gz
d41d8cd98f00b204e9800998ecf8427e  db_snapshot.sql.gz
d41d8cd98f00b204e9800998ecf8427e  images_snapshot.tar
```

![image](https://user-images.githubusercontent.com/639942/111598797-df580600-87cf-11eb-969e-66e5cbf52b5f.png)

![image](https://user-images.githubusercontent.com/639942/111599449-90f73700-87d0-11eb-9991-75e73eb53318.png)

**Comment by jwokaty** [comment]
@lwaldron I'm confirming that I observed the same issues you found with the 21.8KB combined.tar.gz with timestamp 3/18 in GCP.

As for the other versions, if I understand correctly, the backup is always saved to combined.tar.gz and we want to use GCP's object versioning. [Versioning](https://cloud.google.com/storage/docs/using-object-versioning#gsutil_3) was suspended for the bucket so I enabled it. Now we should start see the noncurrent versions with the next backup using gsutil:

```
$ gsutil versioning get gs://backups.bugsigdb.org
gs://backups.bugsigdb.org: Suspended

$ gsutil versioning set on gs://backups.bugsigdb.org
Enabling versioning for gs://backups.bugsigdb.org/...

$ gsutil ls -a gs://backups.bugsigdb.org                            # Lists noncurrent versions
gs://backups.bugsigdb.org/combined.tar.gz#1616047211064355
```

**Comment by lwaldron** [comment]
Thanks @jwokaty!

**Comment by jwokaty** [comment]
@tosfos I think there's still an issue with the backups. They're all 22KB. The image and db files are both size zero.

```
$ gsutil ls -la gs://backups.bugsigdb.org/
     22307  2021-03-18T06:00:11Z  gs://backups.bugsigdb.org/combined.tar.gz#1616047211064355  metageneration=3
     22308  2021-03-19T06:00:08Z  gs://backups.bugsigdb.org/combined.tar.gz#1616133608215772  metageneration=3
     22309  2021-03-20T06:00:08Z  gs://backups.bugsigdb.org/combined.tar.gz#1616220008662103  metageneration=3
     22307  2021-03-21T06:00:11Z  gs://backups.bugsigdb.org/combined.tar.gz#1616306410966189  metageneration=2
     22308  2021-03-22T06:00:07Z  gs://backups.bugsigdb.org/combined.tar.gz#1616392807740462  metageneration=2
     22308  2021-03-23T06:00:08Z  gs://backups.bugsigdb.org/combined.tar.gz#1616479208227545  metageneration=2
     22308  2021-03-24T06:00:08Z  gs://backups.bugsigdb.org/combined.tar.gz#1616565608255485  metageneration=2
     22308  2021-03-25T06:00:07Z  gs://backups.bugsigdb.org/combined.tar.gz#1616652007665351  metageneration=1
TOTAL: 8 objects, 178463 bytes (174.28 KiB)
```

**Comment by tosfos** [comment]
We'll check.

**Comment by tosfos** [comment]
It looks like we were suffering from this issue: https://github.com/docker/compose/issues/3352

Should be all fixed now.

**Comment by jwokaty** [comment]
@tosfos The backups appear to be working correctly.

I am trying to follow the backup restoration process according to your instructions at [README.docker.md](https://github.com/waldronlab/BugSigDB/blob/master/README.docker.mdf) using the docker files you linked to in the issue; however, I can't seem to configure it properly to access the database. What are the minimum settings that must be configured in order to docker-compose up? Are they the values in docker-bugsigdb.org-master/.env_example?

The steps I took based on your instructions are

1. Move db_snapshot.sql to docker-bugsigdb.org-master/__initdb.
2. Move images (from images_snapshot.tar) to docker-bugsigdb.org-master/_data/mediawiki/images.
3. Create an .env with the following environmental variables set:
  MW_DB_NAME
  MW_DB_INSTALLDB_USER # This is set to bugsigdb_user
  MW_DB_INSTALLDB_PASS
  MW_ADMIN_USER
  MW_ADMIN_PASS
4. cd docker-bugsigdb.org-master && sudo docker-compose up.

Then I get the following output:

```{bash}
Creating docker-bugsigdborg_redis_1 ...done
Creating docker-bugsigdborg_db_1    ... done
Creating docker-bugsigdborg_web_1   ... done
Attaching to docker-bugsigdborg_db_1, docker-bugsigdborg_redis_1, docker-bugsigdborg_web_1
web_1    | sending incremental file list
redis_1  | 1:C 08 Apr 2021 21:26:30.260 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 08 Apr 2021 21:26:30.260 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 08 Apr 2021 21:26:30.260 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
db_1     | Check for the need to update the MySQL databases
db_1     | MySQL databases do not need to be upgraded
db_1     | 
web_1    | ./
db_1     | 2021-04-08T21:26:30.600781Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1     | 2021-04-08T21:26:30.601864Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
web_1    | cache/
web_1    | images/
redis_1  | 1:M 08 Apr 2021 21:26:30.261 * monotonic clock: POSIX clock_gettime
db_1     | 2021-04-08T21:26:30.604199Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1     | 2021-04-08T21:26:30.604218Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1     | 2021-04-08T21:26:30.604220Z 0 [Note] InnoDB: Uses event mutexes
db_1     | 2021-04-08T21:26:30.604223Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1     | 2021-04-08T21:26:30.604225Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
db_1     | 2021-04-08T21:26:30.604227Z 0 [Note] InnoDB: Using Linux native AIO
web_1    | 
web_1    | sent 141 bytes  received 27 bytes  336.00 bytes/sec
web_1    | total size is 225  speedup is 1.34
db_1     | 2021-04-08T21:26:30.604411Z 0 [Note] InnoDB: Number of pools: 1
db_1     | 2021-04-08T21:26:30.604483Z 0 [Note] InnoDB: Using CPU crc32 instructions
redis_1  | 1:M 08 Apr 2021 21:26:30.261 * Running mode=standalone, port=6379.
redis_1  | 1:M 08 Apr 2021 21:26:30.261 # Server initialized
redis_1  | 1:M 08 Apr 2021 21:26:30.261 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
db_1     | 2021-04-08T21:26:30.605663Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
web_1    | Check for the need to run maintenance scripts
db_1     | 2021-04-08T21:26:30.611427Z 0 [Note] InnoDB: Completed initialization of buffer pool
redis_1  | 1:M 08 Apr 2021 21:26:30.262 * Loading RDB produced by version 6.2.1
redis_1  | 1:M 08 Apr 2021 21:26:30.262 * RDB age 15 seconds
redis_1  | 1:M 08 Apr 2021 21:26:30.262 * RDB memory usage when created 0.77 Mb
web_1    | Waiting for database to start
db_1     | 2021-04-08T21:26:30.613036Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
redis_1  | 1:M 08 Apr 2021 21:26:30.262 * DB loaded from disk: 0.000 seconds
redis_1  | 1:M 08 Apr 2021 21:26:30.262 * Ready to accept connections
db_1     | 2021-04-08T21:26:30.624672Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1     | 2021-04-08T21:26:30.636785Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1     | 2021-04-08T21:26:30.636844Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1     | 2021-04-08T21:26:30.653696Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1     | 2021-04-08T21:26:30.654419Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1     | 2021-04-08T21:26:30.654429Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1     | 2021-04-08T21:26:30.654750Z 0 [Note] InnoDB: Waiting for purge to start
db_1     | 2021-04-08T21:26:30.704972Z 0 [Note] InnoDB: 5.7.19 started; log sequence number 500257317
db_1     | 2021-04-08T21:26:30.705381Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1     | 2021-04-08T21:26:30.705639Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1     | 2021-04-08T21:26:30.708562Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210408 21:26:30
db_1     | 2021-04-08T21:26:30.712900Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1     | 2021-04-08T21:26:30.713217Z 0 [Warning] CA certificate ca.pem is self signed.
db_1     | 2021-04-08T21:26:30.715987Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1     | 2021-04-08T21:26:30.716160Z 0 [Note] IPv6 is available.
db_1     | 2021-04-08T21:26:30.716176Z 0 [Note]   - '::' resolves to '::';
db_1     | 2021-04-08T21:26:30.716220Z 0 [Note] Server socket created on IP: '::'.
db_1     | 2021-04-08T21:26:30.720594Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-04-08T21:26:30.720652Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-04-08T21:26:30.720682Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-04-08T21:26:30.720692Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-04-08T21:26:30.720711Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-04-08T21:26:30.723195Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-04-08T21:26:30.723220Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-04-08T21:26:30.733141Z 0 [Note] Event Scheduler: Loaded 0 events
db_1     | 2021-04-08T21:26:30.733496Z 0 [Note] mysqld: ready for connections.
db_1     | Version: '5.7.19'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db_1     | 2021-04-08T21:26:30.733523Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
db_1     | 2021-04-08T21:26:30.733535Z 0 [Note] Beginning of list of non-natively partitioned tables
db_1     | 2021-04-08T21:26:30.753795Z 0 [Note] End of list of non-natively partitioned tables
db_1     | 2021-04-08T21:26:30.795124Z 3 [Note] Access denied for user 'bugsigdb_user'@'172.19.0.4' (using password: YES)
web_1    | Waiting for database to start...
web_1    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.19.0.4. Set the 'ServerName' directive globally to suppress this message
db_1     | 2021-04-08T21:26:31.809821Z 4 [Note] Access denied for user 'bugsigdb_user'@'172.19.0.4' (using password: YES)
web_1    | Waiting for database to start...
db_1     | 2021-04-08T21:26:32.824528Z 5 [Note] Access denied for user 'bugsigdb_user'@'172.19.0.4' (using password: YES)
web_1    | Waiting for database to start...
db_1     | 2021-04-08T21:26:33.837113Z 6 [Note] Access denied for user 'bugsigdb_user'@'172.19.0.4' (using password: YES)
web_1    | Waiting for database to start...
db_1     | 2021-04-08T21:26:34.849802Z 7 [Note] Access denied for user 'bugsigdb_user'@'172.19.0.4' (using password: YES)
web_1    | Waiting for database to start...
db_1     | 2021-04-08T21:26:35.861872Z 8 [Note] Access denied for user 'bugsigdb_user'@'172.19.0.4' (using password: YES)
web_1    | Waiting for database to start...
db_1     | 2021-04-08T21:26:36.874476Z 9 [Note] Access denied for user 'bugsigdb_user'@'172.19.0.4' (using password: YES)
```

Checking localhost:8081, I see the following:

![semantic_mediawiki_error](https://user-images.githubusercontent.com/1744257/114100752-c2749700-9892-11eb-855d-b7b85d153712.png)

**Comment by tosfos** [comment]
Sorry about the delay. I'll follow up soon.

**Comment by tosfos** [comment]
This should be fixed now. Please try again.

https://github.com/waldronlab/BugSigDB/commit/b2c26997b29339d3c3ed3c0ead78844b71f3e485

**Comment by jwokaty** [comment]
@tosfos It seems to be able to connect to the database now; however, I'm still getting the Error Schema Invalid Key page. I see the following output on `docker-compose up`. It has an unknown database error when attempting to run `maintenance/update.php`:

```
sudo docker-compose up                                                                                                                                                       
Creating bugsigdb_db_1    ... done                                                                                                                                                                                 
Creating bugsigdb_redis_1 ... done                                                                                                                                                                                 
Creating bugsigdb_web_1   ... done                                                                                                                                                                                 
Attaching to bugsigdb_redis_1, bugsigdb_db_1, bugsigdb_web_1                                                                                                                                                       
db_1     | Check for the need to update the MySQL databases                                                                                                                                                        
db_1     | MySQL databases do not need to be upgraded                                                                                                                                                              
db_1     |                                                                                                                                                                                                         
redis_1  | 1:C 04 May 2021 15:31:59.512 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo                                                                                                                            
redis_1  | 1:C 04 May 2021 15:31:59.513 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=1, just started                                                                                           
redis_1  | 1:C 04 May 2021 15:31:59.513 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf                                      
web_1    | sending incremental file list                                                                                                                                                                           
redis_1  | 1:M 04 May 2021 15:31:59.513 * monotonic clock: POSIX clock_gettime                                                                                                                                     
db_1     | 2021-05-04T15:31:59.855576Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).           
db_1     | 2021-05-04T15:31:59.856666Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...                                                                                                                   
web_1    | ./                                                                                                                                                                                                      
redis_1  | 1:M 04 May 2021 15:31:59.514 * Running mode=standalone, port=6379.                                                                                                                                      
redis_1  | 1:M 04 May 2021 15:31:59.514 # Server initialized                                                                                                                                                       
redis_1  | 1:M 04 May 2021 15:31:59.514 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then
 reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.                                                                                                                                
redis_1  | 1:M 04 May 2021 15:31:59.514 * Loading RDB produced by version 6.2.1                                                                                                                                    
redis_1  | 1:M 04 May 2021 15:31:59.514 * RDB age 7 seconds                                                                                                                                                        
redis_1  | 1:M 04 May 2021 15:31:59.514 * RDB memory usage when created 0.78 Mb                                                                                                                                    
db_1     | 2021-05-04T15:31:59.859225Z 0 [Note] InnoDB: PUNCH HOLE support available                                                                                                                               
db_1     | 2021-05-04T15:31:59.859249Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins                                                                                                               
db_1     | 2021-05-04T15:31:59.859253Z 0 [Note] InnoDB: Uses event mutexes                                                                                                                                         
db_1     | 2021-05-04T15:31:59.859256Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier                                                                                             
db_1     | 2021-05-04T15:31:59.859260Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3                                                                                                                           
db_1     | 2021-05-04T15:31:59.859263Z 0 [Note] InnoDB: Using Linux native AIO                                                                                                                                     
redis_1  | 1:M 04 May 2021 15:31:59.514 * DB loaded from disk: 0.000 seconds
redis_1  | 1:M 04 May 2021 15:31:59.514 * Ready to accept connections
web_1    | cache/                                   
web_1    | images/                                  
db_1     | 2021-05-04T15:31:59.859517Z 0 [Note] InnoDB: Number of pools: 1
web_1    |                                          
web_1    | sent 141 bytes  received 27 bytes  336.00 bytes/sec
web_1    | total size is 225  speedup is 1.34
db_1     | 2021-05-04T15:31:59.859619Z 0 [Note] InnoDB: Using CPU crc32 instructions
web_1    | Check for the need to run maintenance scripts
web_1    | Waiting for database to start
db_1     | 2021-05-04T15:31:59.861036Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1     | 2021-05-04T15:31:59.866889Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1     | 2021-05-04T15:31:59.868250Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1     | 2021-05-04T15:31:59.879767Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1     | 2021-05-04T15:31:59.889836Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1     | 2021-05-04T15:31:59.889901Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1     | 2021-05-04T15:31:59.905978Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1     | 2021-05-04T15:31:59.906666Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1     | 2021-05-04T15:31:59.906674Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1     | 2021-05-04T15:31:59.906971Z 0 [Note] InnoDB: Waiting for purge to start
db_1     | 2021-05-04T15:31:59.957164Z 0 [Note] InnoDB: 5.7.19 started; log sequence number 13252353
db_1     | 2021-05-04T15:31:59.957415Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1     | 2021-05-04T15:31:59.957541Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1     | 2021-05-04T15:31:59.959550Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210504 15:31:59
db_1     | 2021-05-04T15:31:59.960681Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1     | 2021-05-04T15:31:59.960823Z 0 [Warning] CA certificate ca.pem is self signed.
db_1     | 2021-05-04T15:31:59.962555Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1     | 2021-05-04T15:31:59.962666Z 0 [Note] IPv6 is available.
db_1     | 2021-05-04T15:31:59.962674Z 0 [Note]   - '::' resolves to '::';
db_1     | 2021-05-04T15:31:59.962707Z 0 [Note] Server socket created on IP: '::'.
db_1     | 2021-05-04T15:31:59.965826Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.965858Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.965863Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.965874Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.965877Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.965885Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.967709Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.967723Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2021-05-04T15:31:59.970809Z 0 [Note] Event Scheduler: Loaded 0 events
db_1     | 2021-05-04T15:31:59.970959Z 0 [Note] mysqld: ready for connections.
db_1     | Version: '5.7.19'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db_1     | 2021-05-04T15:31:59.970973Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-parti
tion-engine-check' to skip this check.              
db_1     | 2021-05-04T15:31:59.970975Z 0 [Note] Beginning of list of non-natively partitioned tables
db_1     | 2021-05-04T15:31:59.979419Z 0 [Note] End of list of non-natively partitioned tables
web_1    | Successfully connected to the database.
web_1    | Run maintenance script: maintenance/update.php --quick
web_1    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message
web_1    | MediaWiki 1.35.1 Updater
web_1    |                                          
web_1    | Your composer.lock file is up to date with current dependencies!
web_1    | Wikimedia\Rdbms\DBConnectionError from line 1420 of /var/www/html/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php: Cannot access the database: Unknown error (db)
web_1    | #0 /var/www/html/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(934): Wikimedia\Rdbms\LoadBalancer->reportConnectionError()
web_1    | #1 /var/www/html/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(901): Wikimedia\Rdbms\LoadBalancer->getServerConnection()
web_1    | #2 /var/www/html/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1046): Wikimedia\Rdbms\LoadBalancer->getConnection()
web_1    | #3 /var/www/html/w/maintenance/includes/Maintenance.php(1371): Wikimedia\Rdbms\LoadBalancer->getMaintenanceConnectionRef()
web_1    | #4 /var/www/html/w/maintenance/update.php(141): Maintenance->getDB()
web_1    | #5 /var/www/html/w/maintenance/doMaintenance.php(107): UpdateMediaWiki->execute()
web_1    | #6 /var/www/html/w/maintenance/update.php(253): require_once('/var/www/html/w...')
web_1    | #7 {main}
```
I've only set `MW_DB_INSTALLDB_PASS` and `MW_DB_NAME` in my `.env`. I've tried running `setupStore.php` in the web container; however, I get another error. I did a `git pull` and `docker-compose build`. Is there a configuration or a step that I'm missing?

**Comment by tosfos** [comment]
We tried these steps and it worked fine. There was an issue with older database dumps. Can you try again with a recent one?

**Comment by jwokaty** [comment]
I will try with a recent backup; however, I'm getting an authorization error:

```
$ docker-compose up
Pulling web (ghcr.io/wikiteq/mediawiki:1.35.1-20210512-30)...
ERROR: Head https://ghcr.io/v2/wikiteq/mediawiki/manifests/1.35.1-20210512-30: unauthorized
```

**Comment by tosfos** [comment]
Sorry about that. Looks like you caught us in the middle of a change. Will make that public.

**Comment by tosfos** [comment]
Please give this another shot.

**Comment by jwokaty** [comment]
@tosfos I was finally able to `docker-compose up`; however, I just have a few more questions. I set `MW_ADMIN_USER` and `MW_ADMIN_PASS` in my `.env` file; however, I wasn't able to log in--is this supposed to be the existing admin's username and password? I want to confirm that is the case and that it doesn't create another admin account.

Also, do we need to set `MW_NCBI_TAXONOMY_API_KEY`, `MW_RECAPTCHA_SITE_KEY`, `MW_RECAPTCHA_SECRET_KEY` as mentioned in https://github.com/waldronlab/BugSigDB/blob/master/docker-compose.yml#L24-L26? I didn't see recaptcha and I wasn't sure if the NCBI Taxonomy API key was used.

**Comment by tosfos** [comment]
The easiest way to do this would actually be if I sent you the .env file that's in production. It is confidential obviously. Is there a secure way I can send it to you?

To answer your questions:

MW_ADMIN_USER / MW_ADMIN_PASS is only used for fresh database installs (when no dump is provided at __initdb). It will not create or change the admin account for an existing database.

MW_NCBI_TAXONOMY_API_KEY is necessary since the wiki has the NCBITaxonomyLookup extension enabled.

MW_RECAPTCHA_*  is necessary since the wiki has ConfirmEdit [enabled](https://github.com/waldronlab/BugSigDB/blob/master/_resources/CustomSettings.php#L213 ).

Once you have the .env file, you won't need to worry about these.

**Comment by tosfos** [comment]
Can this be closed?

**Comment by lgeistlinger** [comment]
@jwokaty @lwaldron input required.

**Comment by lwaldron** [comment]
@jwokaty let us know, and close the issue after successful restore and checking presence of data, users, and basic functionality of the restored site.

**Comment by jwokaty** [comment]
@tosfos I'm sorry for the delay in following up. Unfortunately, I am again having issues trying to connect to the DB after updating my repo and pulling any new images. I am using the `.env` you put in the Dropbox and a snapshot from earlier this week. I also tried accessing the db directly in the db container using the password but wasn't able to access it. Has the db password changed since you sent the `.env`? Looking at docker compose log, I see the db password that's in the `.env`--should we be doing that?

**Comment by tosfos** [comment]
Thank you for your persistence! It's not the .env file causing problems as it hasn't been changed on the server, and it wouldn't actually matter if it was.

We tested on 2 separate machines and we were able to get the wiki up without issue. Here are some additional instructions that will hopefully help out. Please let me know if you run into any issue at all and I'll be happy to assist. If you could send screenshots or the text of any error messages, that would be great.

**Getting the database**
First you need to get the database itself. The db_snapshot.sql.gz file is extracted from the latest combined.tar.gz backup which is in Google Cloud. It can be downloaded by hand via the Google Cloud console or, if you have 'gsutil' configured, via that tool. If you're not using gsutil, skip the first command here and add the file manually to the working directory.
```
$ gsutil cp gs://backups.bugsigdb.org/combined.tar.gz combined.tar.gz
$ tar -xvzf combined.tar.gz
```
Make note of the path to db_snapshot.sql.gz as it will be needed in the next step.

**Running Docker**
You can follow these instructions.
```
cd ~/
git clone https://github.com/waldronlab/BugSigDB.git
cd BugSigDB
cp /path/to/env/copied/from/production/.env .
# The echo commands below make the container run on localhost:8081
echo "PORT=8081" >> .env
echo "MW_SITE=http://localhost:8081" >> .env
cp /path/to/database/backup/db_snapshot.sql.gz __initdb/
docker-compose up
# Note the `-d` is omitted to have a better look on the output
```
Once that's all done, you should be able to visit a link like http://localhost:8081/Special:RecentChanges. If it loads, you can press   Ctrl+C to stop docker.

**Alternative**
I attached a shell script that will do all the work for you and put the wiki on port 8080. It requires gsutil.

[test_backup.zip](https://github.com/waldronlab/BugSigDB/files/6778668/test_backup.zip)

**Getting the images directory**
These instructions don't cover restoring the images, but we can worry about that next if needed.

**Comment by tosfos** [comment]
After thinking about it some more, I'm wondering if you're experiencing the database issue due to an old database image that's still hanging around. Can you try removing all of your images and starting from scratch?

Please let me know if I can help with this.

**Comment by jwokaty** [comment]
I apologize for the delay. I'll follow up on this by Wednesday at the latest.

**Comment by jwokaty** [comment]
I was able to successfully `docker-compose up` and check users, data, and images. I modified the script and I'm including what worked for me. I ran this manually since there's a part I need to `sudo` to copy the images due to permissions. I also needed to extract the images and insert newlines into the .env. Thanks for your patience. I'm finally closing out this issue.

```
#/bin/bash

echo "Copying the latest archive.."
gsutil cp gs://backups.bugsigdb.org/combined.tar.gz combined.tar.gz
echo "Extracting.."
tar -xvzf combined.tar.gz
echo "Cloning the stack repo.."
git clone https://github.com/waldronlab/BugSigDB.git BugSigDB
echo "Copying the database dump.."
gzip -d db_snapshot.sql.gz
cp db_snapshot.sql BugSigDB/__initdb/
echo "Copy the images"
tar vxf images_snapshot.tar
sudo cp -npR mediawiki/images BugSigDB/_data/mediawiki
echo "Copying the .env.."
cp .env BugSigDB/
echo "Modifying the env to run on localhost:8080.."
echo "\nPORT=8080" >> BugSigDB/.env
echo "\nMW_SITE=http://localhost:8080" >> BugSigDB/.env
echo "Running the stack.."
cd BugSigDB
docker-compose up
```
